#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DisplayPort-2 --primary --mode 1920x1080 --rate 144 --rotate normal --output HDMI-A-0 --mode 2560x1080 --rate 75 --rotate normal --right-of DisplayPort-2

# keyboard typematic delay and rate
xset r rate 250 50
xsetroot -cursor_name left_ptr &

picom &
xwallpaper --zoom ~/Pictures/wall7.jpg

pkill polybar
$HOME/.config/polybar/launch.sh

bspc monitor DisplayPort-2 -d 1 2
bspc monitor HDMI-A-0 -d 3 4 5 6

bsp-layout set tall III -- --master-size 0.5

bspc config focused_border_color "#333333"
bspc config normal_border_color "#0d0d0d"

bspc config border_width         5
bspc config window_gap           8
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config bottom_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a org.wezfurlong.wezterm desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wezterm &
brave &
